# Generated by Django 4.0.4 on 2022-05-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('headline', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=10000)),
                ('summary', models.CharField(max_length=5000)),
            ],
        ),
    ]
